---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "sf-testapp.fullname" . }}-db-config
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": "pre-install"
data:
  DB_HOST: "{{ .Values.DB.host     | b64enc }}"
  DB_NAME: "{{ .Values.DB.name     | b64enc }}"
  DB_USER: "{{ .Values.DB.user     | b64enc }}"
  DB_PASS: "{{ .Values.DB.password | b64enc }}"
