name: Docker Image CI

on:
  push:
    branches: [ "master" ]
    tags: [ 'v*.*.*' ]
    
jobs:

  build:

    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ github.repository }}:${{ steps.meta.outputs.tags }}  # $(date +%s)
